### ISSUE TITLE
Substract is not a word in modern english

### ISSUE THREAD

**Issue by kluzzebass** [Tak-Iwamoto/ptera#35]
The function `substract` should be named `subtract`.

**Comment by Tak-Iwamoto** [comment]
@kluzzebass 
Thanks. 🙏 I'll fix it.

**Comment by Tak-Iwamoto** [comment]
https://github.com/Tak-Iwamoto/ptera/commit/0b208c94afacb70ae564bc827490f53e3d354866
done
